In [1]:
import numpy as np

In [9]:
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(np.__version__)

[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
2.3.2


In [11]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
c=np.array(13)
print(a[1)
print(a.ndim)
print(c)
print(c.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
13
0


In [19]:
a=np.array([1,2,3,4,5],ndmin=4)
print(a[0,0,0,0])
print("the dimension is",a.ndim)

1
the dimension is 4


In [20]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(a):
    print(i)
#np.nditer

1
2
3
4
5
6
7
8
9
10
11
12


In [22]:
a1=[1,2,3]
a2=[4,5,6]
a=np.concatenate((a1,a2))
print(a)

[1 2 3 4 5 6]


In [28]:
a=np.array([1,4,56,9,88,7,3,2,6,4,5])
b=np.where(a==4)
print(b)

(array([1, 9]),)


In [27]:
a=np.array([3,5,46,8])
print(np.sort(a))

[ 3  5  8 46]


In [29]:
a=np.array([23,45,1,56,12])
b=[True,True,False,False,True]
na=a[b]
print(na)

[23 45 12]


In [ ]:
#mean,median,mode
#np.mean(a)